// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherControl.Api.Data;

#nullable disable

namespace TeacherControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608105508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TeacherControl.Api.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinutesLate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mood")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.ReviewTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewTags");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4A90E2",
                            FullName = "Jakub Šenkýř",
                            Initials = "SNJ",
                            Subject = "Vývoj softwaru"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#2ECC71",
                            FullName = "Jakub Lattenberg",
                            Initials = "LAJ",
                            Subject = "Aplikační software"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#E74C3C",
                            FullName = "Marek Šváb",
                            Initials = "SVM",
                            Subject = "Anglický jazyk, Ekonomika"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4D5645",
                            FullName = "Petr Košátko",
                            Initials = "KOP",
                            Subject = "Operační systémy"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#641C34",
                            FullName = "Pavel Bárta",
                            Initials = "BAP",
                            Subject = "Internet věcí"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#063971",
                            FullName = "Jakub Klázar",
                            Initials = "KLJ",
                            Subject = "Mechatronika"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#2E3A23",
                            FullName = "Martina Pradáčová",
                            Initials = "PRM",
                            Subject = "Český jazyk a literatura"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#CAC4B0",
                            FullName = "Andrea Lukáčková",
                            Initials = "LUA",
                            Subject = "Matematika"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#CBD0CC",
                            FullName = "Radana Návratová",
                            Initials = "NAR",
                            Subject = "Občanská nauka"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#A12312",
                            FullName = "Martin Kádrle",
                            Initials = "KAM",
                            Subject = "Tělesná výchova"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#CF3476",
                            FullName = "Jan Nymš",
                            Initials = "NYJ",
                            Subject = "Počítačové sítě"
                        });
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Absence", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Teacher", "Teacher")
                        .WithMany("Absences")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.ReviewTag", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Review", "Review")
                        .WithMany("Tags")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Teacher", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
