// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherControl.Api.Data;

#nullable disable

namespace TeacherControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TeacherControl.Api.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinutesLate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mood")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.ReviewTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewTags");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#e02020",
                            FullName = "Novák Karel",
                            Initials = "NK",
                            Subject = "Matematika · Fyzika · 3. ročník"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#f0a020",
                            FullName = "Procházková Helena",
                            Initials = "PH",
                            Subject = "Český jazyk · Literatura · 2. ročník"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#20a020",
                            FullName = "Vlček Jaroslav",
                            Initials = "VJ",
                            Subject = "Tělocvik · Biologie · 1. ročník"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#888888",
                            FullName = "Krejčí Marie",
                            Initials = "KM",
                            Subject = "Chemie · Fyzika · 3. ročník"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#5080e0",
                            FullName = "Beneš Tomáš",
                            Initials = "BT",
                            Subject = "Dějepis · Zeměpis · 2. ročník"
                        });
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Absence", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Teacher", "Teacher")
                        .WithMany("Absences")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.ReviewTag", b =>
                {
                    b.HasOne("TeacherControl.Api.Models.Review", "Review")
                        .WithMany("Tags")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Review", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TeacherControl.Api.Models.Teacher", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
